"""phase9 chat conversation kind and dm participants

Revision ID: 1789eeffdac9
Revises: 73646fc49bb7
Create Date: 2026-08-21 16:46:46.240862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1789eeffdac9'
down_revision: Union[str, Sequence[str], None] = '73646fc49bb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'user_id')
    )
    op.add_column('conversations', sa.Column('kind', sa.String(), nullable=False, server_default='room'))
    op.alter_column('conversations', 'kind', server_default=None)
    op.drop_constraint(op.f('conversations_project_id_key'), 'conversations', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('conversations_project_id_key'), 'conversations', ['project_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('conversations', 'kind')
    op.drop_table('conversation_participants')
    # ### end Alembic commands ###
